### ISSUE TITLE
Chapter 6 - problem with  loading comments. 

### ISSUE THREAD

**Issue by edxxgardo** [aaronksaunders/AppC-Alloy-Book#5]
Hello Aaron,
I got stuck at the beginning of the Chapter 6. To the point:
File: feed.js
Function:  function handleCommentButtonClicked(_event) 
Expression: var model = collection.get(_event.row.row_id);

Problem:
When I click on the Comment button below the any picture, I get the list of comments (there are already three in ACS for the same picture) and no matter what picture's button I click on, I get the 3 comments, always. I checked and rechecked and for me, the _event.row.row_id is not providing the right Photo id. I tried printing _event.row.row_id in the log and is always undefined.
It goes without saying that I am using the code from the book and I don't really see where the problem is.
Hope you can help me. Thanks a bunch

The book is really good! I love this way of learning with a real project, no just theory ;)

**Comment by edxxgardo** [comment]
Problem solved. The issue was in the $.row.row_id = modelo.model.attributes.id || '';
in the file feedrow.js
Thanks.

**Comment by aaronksaunders** [comment]
Can you please do me a favor and when you get a chance leave a comment on Amazon regarding the book if it has been helpful to you?
