### ISSUE TITLE
processACSComments - "delete" does not call Cloud.Reviews.remove

### ISSUE THREAD

**Issue by newportsolutionsgroup** [aaronksaunders/AppC-Alloy-Book#8]
**UPDATE: The BOOK is correct!**

**The book has the correct "delete" code necessary to remove comments. This GIT repo AppC-Alloy-Book does not contain the code from the book. Of course this is the where I cheated and decided to copy the code from GIT for ACS.js instead of hand coding from the book**

I am working through the entire book to get my head around Alloy after several years or classic Ti experience. 

I'm at the end of chapter 6 and finding that that my Comments are not deleted. 

In the ACS.js processACSComments, **"delete" method does not call Cloud.Reviews.remove** so comments are never deleted. 

Am I missing something!?

**Comment by aaronksaunders** [comment]
I fixed the error thank @newportsolutionsgroup for spotting the issue
